// backend/containers/Login.tsx
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { executeRequest } from "../services/api";
import { AccessTokenProps } from "../types/AccessTokenProps";

const Login: NextPage<AccessTokenProps> = ({ setAccessToken }) => {
    const [login, setLogin] = useState("juancarielo@gmail.com");
    const [password, setPassword] = useState("Admin@123");

    const [msgErro, setMsgErro] = useState("");
    const [isLoading, setLoading] = useState(false);

    const doLogin = async (e: any) => {
        try {
            setLoading(true);
            e.preventDefault();

            if (!login || !password) {
                setMsgErro("Parâmetros de entrada inválidos");
                setLoading(false);
                return;
            }

            const body = {
                login,
                password,
            };

            const result = await executeRequest("login", "POST", body);

            setMsgErro("");

            if (result && result.data) {
                console.log(result);

                localStorage.setItem("accessToken", result.data.token);
                localStorage.setItem("userName", result.data.name);
                localStorage.setItem("userEmail", result.data.email);

                setAccessToken(result.data.token);
            } else {
                setMsgErro("Não foi possível realizar o login, tente novamente!");
            }
        } catch (e: any) {
            // console.log(e);
            setMsgErro("Ocorreu um erro ao processar o login, tente novamente!");
        }

        setLoading(false);
    };

    return (
        <div className="container-login">
            <Head>
                <title>Login</title>
            </Head>

            <img src="/logo.svg" alt="Logo Fiap" className="logo" />

            <form>
                {msgErro && <p>{msgErro}</p>}

                <div className="input">
                    <img src="/mail.svg" alt="Fiap" />
                    <input type="text" value={login} onChange={(e) => setLogin(e.target.value)} />
                </div>

                <div className="input">
                    <img src="/lock.svg" alt="Fiap" />
                    <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
                </div>

                <button className={isLoading ? "disabled" : ""} type="button" onClick={doLogin} disabled={isLoading}>
                    {isLoading ? "Carregando..." : "Login"}
                </button>
            </form>
        </div>
    );
};

export { Login };

// vue/src/components/pages/Login.vue
<template>
    <div class="container-login">
        <img src="../../assets/images/logo.svg" alt="Logo Fiap" class="logo" />

        <form>
            <p>{{ msgErro }}</p>

            <div class="input">
                <img src="../../assets/images/mail.svg" alt="E-mail" />
                <input
                    type="text"
                    placeholder="Informe seu e-mail"
                    v-model="body.login"
                />
            </div>

            <div class="input">
                <img src="../../assets/images/lock.svg" alt="Senha" />
                <input
                    type="password"
                    placeholder="Informe sua senha"
                    v-model="body.password"
                />
            </div>

            <button class="" type="button" @click="doLogin">
                {{ labelButton }}
            </button>
        </form>
    </div>
</template>

<script>
export default {
    data() {
        return {
            msgErro: "",
            labelButton: "Login",
            disabledButton: false,
            body: {
                login: "admin@admin.com",
                password: "Admin@123"
            }
        };
    },
    methods: {
        doLogin() {
            // console.log(this.body);

            if (!this.body.login || !this.body.password) {
                this.msgErro = "Favor informar usuario e senha";
                return;
            }

            this.disabledButton = true;
            this.labelButton = "Carregando...";

            this.$http
                .post("login", this.body)
                .then(response => response.json())
                .then(result => {
                    // console.log(result)

                    this.disabledButton = false;
                    this.labelButton = "Login";

                    localStorage.setItem("accessToken", result.token);
                    localStorage.setItem("userName", result.name);
                    localStorage.setItem("userEmail", result.email);

                    this.$emit('token', result.token);
                })
                .catch(e => {
                    // console.log(e)
                    // console.log(e.body.error)

                    if (e && e.body && e.body.error) {
                        this.msgErro = e.body.error;
                    } else {
                        this.msgErro =
                            "Não foi possível autenticar, tente novamente";
                    }
                });
        }
    }
};
</script>

<style lang="scss"></style>
