// vue/src/components/pages/Home.vue
<template>
    <div class="container-home">
        <myHeader @doLogout="sair" />
        <myFilter
            :finishPrevisionStart="finishPrevisionStart"
            :finishPrevisionEnd="finishPrevisionEnd"
            :status="status"
            @setSinishPrevisionStart="setSinishPrevisionStart"
            @setSinishPrevisionEnd="setSinishPrevisionEnd"
            @setStatus="setStatus"
        />
        <myList :tasks="tasks" />
        <myFooter />
    </div>
</template>
<script>
import Header from "../shared/Header.vue";
import Footer from "../shared/Footer.vue";
import Filter from "../shared/Filter.vue";
import List from "../shared/List.vue";
export default {
    data() {
        return {
            finishPrevisionStart: "2021-10-01",
            finishPrevisionEnd: "2021-10-31",
            status: 2,
            tasks: []
        };
    },
    created() {
        this.getTasksWithFilters();
    },
    components: {
        myHeader: Header,
        myFooter: Footer,
        myFilter: Filter,
        myList: List
    },
    methods: {
        sair() {
            this.$emit("token", "");
        },
        setSinishPrevisionStart(d) {
            this.finishPrevisionStart = d;
            this.getTasksWithFilters();
        },
        setSinishPrevisionEnd(d) {
            this.finishPrevisionEnd = d;
            this.getTasksWithFilters();
        },
        setStatus(s) {
            this.status = s;
            this.getTasksWithFilters();
        },
        getTasksWithFilters() {
            let filtros = "?status=" + this.status;

            if (this.finishPrevisionStart) {
                filtros += "&finishPrevisionStart=" + this.finishPrevisionStart;
            }

            if (this.finishPrevisionEnd) {
                filtros += "&finishPrevisionEnd=" + this.finishPrevisionEnd;
            }

            const token = localStorage.getItem("accessToken");

            this.$http
                .get("task" + filtros, {
                    headers: { Authorization: "Bearer " + token }
                })
                .then(r => r.json())
                .then(result => {
                    this.tasks = result;
                });
        }
    }
};
</script>
<style lang="scss"></style>

// backend/containers/Home.tsx
import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import { AccessTokenProps } from "../types/AccessTokenProps";
import { Task } from "../types/Task";
import { Header } from "../components/Header";
import { Filter } from "../components/Filter";
import { List } from "../components/List";
import { Footer } from "../components/Footer";
import { executeRequest } from "../services/api";

const Home: NextPage<AccessTokenProps> = ({ setAccessToken }) => {
    const [tasks, setTasks] = useState<Task[]>([]);
    const [periodoDe, setPeriodoDe] = useState("");
    const [periodoAte, setPeriodoAte] = useState("");
    const [status, setStatus] = useState(0);

    const sair = () => {
        localStorage.removeItem("accessToken");
        localStorage.removeItem("userName");
        localStorage.removeItem("userEmail");

        setAccessToken("");
    };

    const getFilteredList = async () => {
        try {
            let filtros = "?status=" + status;

            if (periodoDe) {
                filtros += "&finishPrevisionStart=" + periodoDe;
            }

            if (periodoAte) {
                filtros += "&finishPrevisionEnd=" + periodoAte;
            }

            console.log(filtros)
            const result = await executeRequest("task" + filtros, "GET");
            if (result && result.data) {
                setTasks(result.data);
            }
        } catch (e) {
            console.log(e);
        }
    };

    useEffect(() => {
        getFilteredList();
    }, [periodoDe, periodoAte, status]);

    return (
        <>
            <Head>
                <title>Home</title>
            </Head>

            <Header sair={sair} />

            <Filter
                periodoDe={periodoDe}
                periodoAte={periodoAte}
                status={status}
                setPeriodoDe={setPeriodoDe}
                setPeriodoAte={setPeriodoAte}
                setStatus={setStatus}
            />

            <List tasks={tasks} />

            {/* <Footer /> */}
        </>
    );
};

export { Home };
