// vue/src/components/shared/Footer.vue
<template>
    <div class="container-footer">
        <button><img src="../../assets/images/add.svg" alt="Adicionar tarefa"></img> Adicionar Tarefa</button>
        <span>© Copyright {{getDate}} Fiap. Todos os direitos reservados.</span>
    </div>
</template>

<script>
export default {
    computed: {
        getDate(){
            return new Date().getFullYear();
        }
    },
};
</script>

<style lang="scss"></style>

// backend/components/Footer.tsx
import type { NextPage } from 'next'

type FooterProps = {
  setShowModal(b:boolean):void
}

const Footer: NextPage<FooterProps> = ({}) => {
  return (
    <div className="container-footer">
        <button><img src="/add.svg" alt="Adicionar tarefa"></img> Adicionar Tarefa</button>
        <span>© Copyright {new Date().getFullYear()} Fiap. Todos os direitos reservados.</span>
    </div>
  )
}

export { Footer }
