// vue/src/components/shared/Header.vue
<template>
    <div class="container-header">
        <img src="../../assets/images/logo.svg" alt="Logo Fiap" class="logo" />
        <button><span>+</span> Adicionar Tarefa</button>
        <div class="mobile">
            <span>Olá, {{ userName }}</span>
            <img
                src="../../assets/images/exit-mobile.svg"
                alt="Deslogar"
                @click="doLogout"
            />
        </div>
        <div class="desktop">
            <span>Olá, {{ userName }}</span>
            <img
                src="../../assets/images/exit-desktop.svg"
                alt="Deslogar"
                @click="doLogout"
            />
        </div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            userName: localStorage.getItem("userName")
        };
    },
    methods: {
        doLogout() {
            localStorage.removeItem("accessToken");
            localStorage.removeItem("userName");
            localStorage.removeItem("userEmail");

            this.$emit("doLogout");
        }
    }
};
</script>

<style lang="scss"></style>

// backend/components/Header.tsx
import type { NextPage } from 'next'

type HeaderProps = {
    sair(): void
    setShowModal(b: boolean): void
}

const Header: NextPage<HeaderProps> = ({ sair, setShowModal }) => {
    const fullName = localStorage.getItem('userName')
    const userName = fullName?.split(' ')[0]

    return (
        <div className="container-header">
            <img src="/logo.svg" alt="Logo Fiap" className="logo" />
            <button onClick={() => setShowModal(true)}>
                <span>+</span> Adicionar Tarefa
            </button>
            <div className="mobile">
                <span>Olá, {userName}</span>
                <img src="/exit-mobile.svg" alt="Deslogar" onClick={sair} />
            </div>
            <div className="desktop">
                <span>Olá, {userName}</span>
                <img src="/exit-desktop.svg" alt="Deslogar" onClick={sair} />
            </div>
        </div>
    )
}

export { Header }
