// vue/src/components/shared/Item.vue
<template>
    <div class="container-item" :class="getClassAtivo">
        <img :src="getImgSrc" :alt="getImgAlt" />
        <div>
            <p :class="getClassConcluido">{{ task && task.name }}</p>
            <span>{{ getDateText }}</span>
        </div>
    </div>
</template>
<script>
import moment from "moment";
export default {
    props: {
        task: {
            name: "",
            finishDate: "",
            finishPrevisionDate: ""
        }
    },
    computed: {
        getClassAtivo() {
            if (this.task && this.task.finishDate) {
                return "";
            }

            return "ativo";
        },
        getClassConcluido() {
            if (this.task && this.task.finishDate) {
                return "concluido";
            }

            return "";
        },
        getImgSrc() {
            if (this.task && this.task.finishDate) {
                return require("../../assets/images/finished.svg");
            }

            return require("../../assets/images/not-finished.svg");
        },
        getImgAlt() {
            if (this.task && this.task.finishDate) {
                return "Tarefa concluída";
            }

            return "Tarefa não concluída";
        },
        getDateText() {
            if (this.task && this.task.finishDate) {
                return `Concluído em: ${moment(this.task.finishDate).format(
                    "DD/MM/yyyy"
                )}`;
            }
            if (this.tasks && this.task.finishPrevisionDate) {
                return `Previsão de conclusão em: ${moment(
                    this.task.finishPrevisionDate
                ).format("DD/MM/yyyy")}`;
            }
            return "Previsão de conclusão em:";
        }
    }
};
</script>
<style lang="scss"></style>

// backend/components/Item.tsx
import type { NextPage } from "next";
import moment from "moment";
import { Task } from "../types/Task";

type ItemProps = {
    task: Task;
};

const Item: NextPage<ItemProps> = ({ task }) => {
    const getDateText = (finishedDate: Date | undefined, finishedPrevisionDate: Date) => {
        if (finishedDate) {
            return `Concluído em: ${moment(finishedDate).format("DD/MM/yyy")}`;
        }

        return `Previsão de conclusão em: ${moment(finishedPrevisionDate).format("DD/MM/yyy")}`;
    };

    return (
        <div className={"container-item" + (task.finishDate ? "" : " ativo")}>
            <img
                src={task.finishDate ? "/finished.svg" : "/not-finished.svg"}
                alt={task.finishDate ? "Tarefa concluída" : "Tarefa não concluída"}
            />

            <div>
                <p className={task.finishDate ? "concluido" : ""}>{task.name}</p>
                <span>{getDateText(task.finishDate, task.finishPrevisionDate)}</span>
            </div>
        </div>
    );
};

export { Item };
